# Generated by Django 5.1.3 on 2025-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_expert_groups_alter_expert_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="specialties",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
