# Generated by Django 5.1.3 on 2025-07-24 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_add_chat_message_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_accepted", models.BooleanField()),
                ("privacy_accepted", models.BooleanField()),
                ("ai_disclaimer_accepted", models.BooleanField()),
                ("age_confirmed", models.BooleanField()),
                ("marketing_consent", models.BooleanField(default=False)),
                ("consent_version", models.CharField(default="1.0", max_length=10)),
                ("expert_name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("referrer", models.URLField(blank=True, null=True)),
                ("page_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "consent_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_session_597c4e_idx",
            old_name="chat_message_session_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_role_ddd811_idx",
            old_name="chat_message_role_idx",
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_price",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="consent_rec_ip_addr_5f87b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["expert_name", "created_at"],
                name="consent_rec_expert__dced66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["user", "created_at"], name="consent_rec_user_id_7e52e7_idx"
            ),
        ),
    ]
