# Generated by Django 5.1.3 on 2025-07-31 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_add_chat_message_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnhancedMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("psychological_tags", models.JSONField(default=list)),
                ("emotional_context", models.CharField(blank=True, max_length=50)),
                ("values_involved", models.JSONField(default=list)),
                ("memory_type", models.CharField(default="experience", max_length=50)),
                ("confidence_score", models.FloatField(default=1.0)),
                ("source", models.CharField(default="interview", max_length=100)),
                ("vector_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enhanced_memories",
                "ordering": ["-confidence_score", "-last_accessed"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Psychological Interview", max_length=200),
                ),
                ("interviewer", models.CharField(blank=True, max_length=100)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="interviews/"),
                ),
                ("transcript", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("transcribing", "Transcribing"),
                            ("processing", "Processing Psychology"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("raw_psychological_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "interviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonaSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("research", "Market Research"),
                            ("interview", "Interview"),
                            ("testing", "Product Testing"),
                        ],
                        default="research",
                        max_length=20,
                    ),
                ),
                ("research_objective", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("research_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "persona_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PsychologicalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("core_values", models.JSONField(default=list)),
                ("fears", models.JSONField(default=list)),
                ("motivations", models.JSONField(default=list)),
                ("decision_patterns", models.JSONField(default=dict)),
                ("emotional_triggers", models.JSONField(default=list)),
                ("contradictions", models.JSONField(default=list)),
                ("communication_style", models.JSONField(default=dict)),
                ("personality_traits", models.JSONField(default=dict)),
                ("worldview", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confidence_score", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "psychological_profiles",
            },
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_session_597c4e_idx",
            old_name="chat_message_session_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_role_ddd811_idx",
            old_name="chat_message_role_idx",
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_price",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="enhancedmemory",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enhanced_memories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personasession",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persona_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personasession",
            name="researcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="psychologicalprofile",
            name="expert",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="psychological_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
