# Generated by Django 5.1.3 on 2025-03-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_expert_bio_expert_specialties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
