# Generated by Django 5.1.3 on 2025-08-12 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_add_chat_message_only"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_session_597c4e_idx",
            old_name="chat_message_session_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_role_ddd811_idx",
            old_name="chat_message_role_idx",
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_price",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
