# Generated by Django 5.1.3 on 2025-06-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_make_user_slug_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="monetization_price",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
