# Generated by Django 5.1.3 on 2025-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_monetization_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
