# Generated by Django 5.1.3 on 2025-03-26 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_onboardingquestion_remove_expert_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmessage",
            name="knowledge_area",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trainingmessage",
            name="role",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name="trainingmessage",
            table=None,
        ),
        migrations.CreateModel(
            name="ExpertKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("knowledge_areas", models.JSONField(default=dict)),
                ("context_vectors", models.JSONField(default=dict)),
                ("training_summary", models.TextField(blank=True)),
                (
                    "expert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_base",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("context_depth", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("confidence_score", models.FloatField(default=1.0)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="api.expertknowledgebase",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trainingmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-last_accessed"],
            },
        ),
    ]
