# Generated by Django 5.1.3 on 2025-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_trainingmessage_knowledge_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
