# Generated by Django 5.1.3 on 2025-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_expert_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
