# Generated by Django 5.1.3 on 2025-05-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
