# Generated by Django 5.1.3 on 2025-05-14 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_user_managers_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
