# Generated by Django 5.1.3 on 2025-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_user_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="verification_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
