# Generated by Django 5.1.3 on 2025-06-06 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_user_options_user_bio_user_last_training_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
