# Generated by Django 5.1.3 on 2025-06-06 09:25

from django.db import migrations


def clear_admin_logs(apps, schema_editor):
    """Clear admin logs that might have bigint foreign keys conflicting with UUID user IDs"""
    try:
        # Get the LogEntry model from django.contrib.admin
        from django.contrib.admin.models import LogEntry
        
        # Clear all admin log entries to prevent bigint = uuid conflicts
        LogEntry.objects.all().delete()
        print("Successfully cleared admin log entries")
    except Exception as e:
        print(f"Error clearing admin logs: {e}")
        # Don't fail the migration if this doesn't work


def reverse_clear_admin_logs(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fix_expert_id_field'),
    ]

    operations = [
        migrations.RunPython(clear_admin_logs, reverse_clear_admin_logs),
    ]
