# Generated by Django 5.1.3 on 2025-06-06 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_fix_admin_log_table_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="expertknowledgebase",
            table="expert_knowledge_bases",
        ),
    ]
