# Generated by Django 5.1.3 on 2025-06-06 10:05

from django.db import migrations

def fix_expert_profiles_table(apps, schema_editor):
    """Fix expert_profiles table to use UUID for expert_id field"""
    
    with schema_editor.connection.cursor() as cursor:
        try:
            # First, clear all expert profile entries to avoid conflicts
            cursor.execute("DELETE FROM expert_profiles;")
            
            # Drop the foreign key constraint if it exists
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name = 'expert_profiles' 
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%expert_id%'
            """)
            
            fk_constraints = cursor.fetchall()
            for constraint in fk_constraints:
                cursor.execute(f"ALTER TABLE expert_profiles DROP CONSTRAINT {constraint[0]};")
            
            # Change expert_id column from bigint to UUID
            cursor.execute("""
                ALTER TABLE expert_profiles 
                ALTER COLUMN expert_id TYPE UUID USING expert_id::text::uuid;
            """)
            
            # Recreate the foreign key constraint
            cursor.execute("""
                ALTER TABLE expert_profiles 
                ADD CONSTRAINT expert_profiles_expert_id_fkey 
                FOREIGN KEY (expert_id) REFERENCES api_user(id) ON DELETE CASCADE;
            """)
            
            print("Successfully fixed expert_profiles table structure")
            
        except Exception as e:
            print(f"Error fixing expert_profiles table: {e}")
            # Continue without failing the migration
            pass

def reverse_fix_expert_profiles_table(apps, schema_editor):
    """Reverse the expert_profiles table fix"""
    # This is irreversible, so we'll just pass
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_expert_id_alter_expertknowledgebase_table'),
    ]

    operations = [
        migrations.RunPython(fix_expert_profiles_table, reverse_fix_expert_profiles_table),
    ] 