# Generated by Django 5.1.3 on 2025-06-06 10:10

from django.db import migrations

def fix_onboarding_answers_table(apps, schema_editor):
    """Fix onboarding_answers table to use UUID for expert_id field"""
    
    with schema_editor.connection.cursor() as cursor:
        try:
            # First, clear all onboarding answer entries to avoid conflicts
            cursor.execute("DELETE FROM onboarding_answers;")
            
            # Drop the foreign key constraint if it exists
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name = 'onboarding_answers' 
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%expert_id%'
            """)
            
            fk_constraints = cursor.fetchall()
            for constraint in fk_constraints:
                cursor.execute(f"ALTER TABLE onboarding_answers DROP CONSTRAINT {constraint[0]};")
            
            # Change expert_id column from bigint to UUID
            cursor.execute("""
                ALTER TABLE onboarding_answers 
                ALTER COLUMN expert_id TYPE UUID USING expert_id::text::uuid;
            """)
            
            # Recreate the foreign key constraint
            cursor.execute("""
                ALTER TABLE onboarding_answers 
                ADD CONSTRAINT onboarding_answers_expert_id_fkey 
                FOREIGN KEY (expert_id) REFERENCES api_user(id) ON DELETE CASCADE;
            """)
            
            print("Successfully fixed onboarding_answers table structure")
            
        except Exception as e:
            print(f"Error fixing onboarding_answers table: {e}")
            # Continue without failing the migration
            pass

def reverse_fix_onboarding_answers_table(apps, schema_editor):
    """Reverse the onboarding_answers table fix"""
    # This is irreversible, so we'll just pass
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fix_expert_profiles_uuid'),
    ]

    operations = [
        migrations.RunPython(fix_onboarding_answers_table, reverse_fix_onboarding_answers_table),
    ] 