# Generated by Django 5.1.3 on 2025-06-06 10:58

from django.db import migrations

def fix_expert_documents_table(apps, schema_editor):
    """Fix expert_documents table to use UUID for expert_id field"""
    
    with schema_editor.connection.cursor() as cursor:
        try:
            # First, clear all document entries to avoid conflicts
            cursor.execute("DELETE FROM expert_documents;")
            
            # Drop the foreign key constraint if it exists
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name = 'expert_documents' 
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%expert_id%'
            """)
            
            fk_constraints = cursor.fetchall()
            for constraint in fk_constraints:
                cursor.execute(f"ALTER TABLE expert_documents DROP CONSTRAINT {constraint[0]};")
            
            # Change expert_id column from bigint to UUID
            cursor.execute("""
                ALTER TABLE expert_documents 
                ALTER COLUMN expert_id TYPE UUID USING expert_id::text::uuid;
            """)
            
            # Recreate the foreign key constraint
            cursor.execute("""
                ALTER TABLE expert_documents 
                ADD CONSTRAINT expert_documents_expert_id_fkey 
                FOREIGN KEY (expert_id) REFERENCES api_user(id) ON DELETE CASCADE;
            """)
            
            print("Successfully fixed expert_documents table structure")
            
        except Exception as e:
            print(f"Error fixing expert_documents table: {e}")
            # Continue without failing the migration
            pass

def reverse_fix_expert_documents_table(apps, schema_editor):
    """Reverse the expert_documents table fix"""
    # This is irreversible, so we'll just pass
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fix_onboarding_answers_uuid'),
    ]

    operations = [
        migrations.RunPython(fix_expert_documents_table, reverse_fix_expert_documents_table),
    ] 