# Generated by Django 5.1.3 on 2025-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_fix_training_tables_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="industry",
            field=models.TextField(),
        ),
    ]
