# Generated by Django 5.1.3 on 2025-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_fix_expert_profile_industry_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("expert", "Expert"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
