# Generated by Django 5.1.3 on 2025-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_change_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_change_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
