# Generated by Django 5.1.3 on 2025-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_consultationsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="knowledge_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="knowledge_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingmessage",
            name="knowledge_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainingmessage",
            name="knowledge_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
