[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health/"
buildCommand = "./setup.sh"
startCommand = "cd backend && npm start"

[variables]
NODE_ENV = "production"
RAILWAY_DOCKERFILE_PATH = "Dockerfile" 