[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health/"
buildCommand = "pip install -r backend/requirements-railway.txt && cd backend && python manage.py migrate"
startCommand = "cd backend && npm start"

[variables]
NODE_ENV = "production"
RAILWAY_DOCKERFILE_PATH = "Dockerfile" 