[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health/"
numReplicas = 1
startCommand = "/app/start-django.sh"

[variables]
NODE_ENV = "production" 