[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildCommand = ""

[deploy]
startCommand = ""
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 