[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 3
restartPolicyMaxRetries = 10
numReplicas = 1

[variables]
NODE_ENV = "production"
PORT = "80" 