[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicyMaxRetries = 5
numReplicas = 1
startCommand = "/bin/bash /app/start.sh"

[variables]
PORT = "8000"
PYTHON_VERSION = "3.10.0"
DATABASE_URL = "${DATABASE_URL}"
DJANGO_SETTINGS_MODULE = "expert_system.settings"
RAILWAY_DEPLOYMENT = "true"
DEBUG = "True"
PYTHONPATH = "/app" 