[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./railway-run.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[variables]
RAILWAY_DOCKERFILE_PATH = "Dockerfile" 