[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyMaxRetries = 5
numReplicas = 1

[variables]
PORT = "8000"
NODE_ENV = "production" 