[build]
builder = "NIXPACKS"
buildCommand = "./setup.sh"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health/"
startCommand = "node backend/server.js"

[variables]
NODE_ENV = "production" 