[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health/"
buildCommand = "pip install -r backend/requirements-railway.txt"
startCommand = "cd backend && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"

[variables]
RAILWAY_DOCKERFILE_PATH = "Dockerfile" 