[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/static/health.json"
healthcheckTimeout = 30
restartPolicyMaxRetries = 10
numReplicas = 1

[variables]
NODE_ENV = "production" 