[build]
builder = "nixpacks"
buildCommand = "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py && pip install -r backend/requirements.txt"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 