[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 5
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"
NODE_ENV = "production" 