[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r /app/backend/requirements.txt"
]

[start]
cmd = "gunicorn --pythonpath /app/backend expert_system.wsgi:application --log-file -"

[variables]
PYTHONPATH = "/app:/app/backend" 