[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "pip install djangorestframework-simplejwt==5.3.1 PyJWT==2.8.0",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd . && gunicorn expert_system.wsgi:application --log-file -" 