[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn expert_system.wsgi:application --log-file -"

[variables]
PYTHONPATH = "/app:/app/backend" 