[phases.setup]
nixpkgs = ["python39", "gcc"]
aptPkgs = ["libpq-dev", "python3-dev"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements-railway.txt",
  "pip install gunicorn==21.2.0 djangorestframework-simplejwt==5.3.1 PyJWT==2.8.0"
]

[start]
cmd = "gunicorn expert_system.wsgi:application --log-file -" 