[build]
builder = "paketobuildpacks/builder:base"

[build.env]
BP_PYTHON_VERSION = "3.9.18"

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install djangorestframework-simplejwt==5.3.1 PyJWT==2.8.0 gunicorn==21.2.0"
]

[start]
cmd = "cd /backend && gunicorn expert_system.wsgi:application --log-file -" 